#!/bin/sh

set -e

sqlite3 data/recipe.db <<EOF
create table if not exists recipes (
  url text primary key,
  summary text,
  lastAccess datetime
);

DROP TABLE IF EXISTS fts;

CREATE VIRTUAL TABLE fts USING fts5(
  url UNINDEXED,
  summary,
  content='recipes',
  prefix='1 2 3',
  tokenize='porter unicode61'
);

-- Triggers to keep the FTS index up to date.
DROP TRIGGER IF EXISTS recipes_ai;
CREATE TRIGGER recipes_ai AFTER INSERT ON recipes BEGIN
  INSERT INTO fts(rowid, url, summary) VALUES (new.rowid, new.url, new.summary);
END;

DROP TRIGGER IF EXISTS recipes_ad;
CREATE TRIGGER recipes_ad AFTER DELETE ON recipes BEGIN
  INSERT INTO fts(fts, rowid, url, summary) VALUES('delete', old.rowid, old.url, old.summary);
END;

DROP TRIGGER IF EXISTS recipes_au;
CREATE TRIGGER recipes_au AFTER UPDATE ON recipes BEGIN
  INSERT INTO fts(fts, rowid, url, summary) VALUES('delete', old.rowid, old.url, old.summary);
  INSERT INTO fts(rowid, url, summary) VALUES (new.rowid, new.url, new.summary);
END;

INSERT INTO fts(fts) VALUES('rebuild');
EOF
